In [10]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torchvision
import torchinfo

# Python basic

## numpy.repeat

In [168]:
m= np.round(np.random.uniform(0,2,size=(1,1,2,3)), 2)
m2= np.repeat(np.repeat(m,3,axis=1),2,axis=0)
print(f'm= {m}, {m.shape}')
print(f'm2= {m2}, {m2.shape}')

m= [[[[1.61 0.68 0.06]
   [1.53 0.2  0.54]]]], (1, 1, 2, 3)
m2= [[[[1.61 0.68 0.06]
   [1.53 0.2  0.54]]

  [[1.61 0.68 0.06]
   [1.53 0.2  0.54]]

  [[1.61 0.68 0.06]
   [1.53 0.2  0.54]]]


 [[[1.61 0.68 0.06]
   [1.53 0.2  0.54]]

  [[1.61 0.68 0.06]
   [1.53 0.2  0.54]]

  [[1.61 0.68 0.06]
   [1.53 0.2  0.54]]]], (2, 3, 2, 3)


## numpy.argsort

In [7]:
a= np.round(np.random.uniform(0,10,size=10),1)
print(f'a= {a}')
print(f'sorted indexes: {np.argsort(a)}')
print(f'        values: {a[np.argsort(a)]}')
print(f'sorted indexes (rev): {np.argsort(a)[::-1]}')
print(f'              values: {a[np.argsort(a)[::-1]]}')

a= [9.  2.1 6.4 3.6 6.9 0.7 2.1 9.3 0.5 1.5]
sorted indexes: [8 5 9 1 6 3 2 4 0 7]
        values: [0.5 0.7 1.5 2.1 2.1 3.6 6.4 6.9 9.  9.3]
sorted indexes (rev): [7 0 4 2 3 6 1 9 5 8]
              values: [9.3 9.  6.9 6.4 3.6 2.1 2.1 1.5 0.7 0.5]


## numpy.argpartition

In [9]:
a= np.round(np.random.uniform(0,10,size=10),1)
def argsort_N(a, N, reverse=False):
  if not reverse:
    idxes= np.argpartition(a,N)[:N]
    return idxes[np.argsort(a[idxes])]
  else:
    idxes= np.argpartition(a,-N)[-N:]
    return idxes[np.argsort(a[idxes])[::-1]]
print(f'a= {a}')
print(f'lowest 3 indexes: {np.argpartition(a,3)[:3]}')
print(f'          values: {a[np.argpartition(a,3)[:3]]}')
print(f'  sorted indexes: {argsort_N(a,3)}')
print(f'          values: {a[argsort_N(a,3)]}')
print(f'   other indexes: {np.argpartition(a,3)[3:]}')
print(f'          values: {a[np.argpartition(a,3)[3:]]}')

print(f'highest 3 indexes: {np.argpartition(a,-3)[-3:]}')
print(f'           values: {a[np.argpartition(a,-3)[-3:]]}')
print(f'   sorted indexes: {argsort_N(a,3,reverse=True)}')
print(f'           values: {a[argsort_N(a,3,reverse=True)]}')
print(f'    other indexes: {np.argpartition(a,-3)[:-3]}')
print(f'           values: {a[np.argpartition(a,-3)[:-3]]}')

a= [3.3 4.2 3.3 7.5 5.1 7.6 4.  6.8 1.  0.8]
lowest 3 indexes: [8 9 0]
          values: [1.  0.8 3.3]
  sorted indexes: [9 8 0]
          values: [0.8 1.  3.3]
   other indexes: [2 6 1 4 7 5 3]
          values: [3.3 4.  4.2 5.1 6.8 7.6 7.5]
highest 3 indexes: [7 3 5]
           values: [6.8 7.5 7.6]
   sorted indexes: [5 3 7]
           values: [7.6 7.5 6.8]
    other indexes: [8 9 0 1 6 2 4]
           values: [1.  0.8 3.3 4.2 4.  3.3 5.1]


## Broadcast

In [15]:
A= np.round(np.random.uniform(0,1,size=(3,4)), 1)
B= np.round(np.random.uniform(0,1,size=(4,3)), 1)
c= np.round(np.random.uniform(0,3,size=(3,)), 0)
print(f'A= {A}')
print(f'B= {B}')
print(f'c= {c}')
print(f'A@B= {A@B}')
print(f'A@B+c= {A@B+c}')
print(f'A@B+c.reshape((3,1))= {A@B+c.reshape((3,1))}')

A= [[1.  0.1 0.4 0.4]
 [0.1 0.5 0.7 0. ]
 [0.2 0.7 0.1 1. ]]
B= [[0.4 0.1 0.7]
 [0.4 0.4 0.3]
 [0.6 0.3 0. ]
 [0.2 0.6 1. ]]
c= [2. 1. 1.]
A@B= [[0.76 0.5  1.13]
 [0.66 0.42 0.22]
 [0.62 0.93 1.35]]
A@B+c= [[2.76 1.5  2.13]
 [2.66 1.42 1.22]
 [2.62 1.93 2.35]]
A@B+c.reshape((3,1))= [[2.76 2.5  3.13]
 [1.66 1.42 1.22]
 [1.62 1.93 2.35]]


## Einsum

In [2]:
A= np.round(np.random.uniform(0,2,size=(3,4)), 2)
B= np.round(np.random.uniform(-1,1,size=(4,3)), 2)
print(f'A= {A}')
print(f'B= {B}')
print(f'A@B= {A@B}')
print(f"ik,kj->ij= {np.einsum('ik,kj->ij',A,B)}")
print(f'A*(B.T)= {A*(B.T)}')
print(f"ij,ji->ij= {np.einsum('ij,ji->ij',A,B)}")

A= [[0.27 1.72 0.99 0.78]
 [0.4  0.43 1.34 1.19]
 [0.12 0.28 0.34 1.68]]
B= [[-0.23  0.74 -0.15]
 [ 0.64  0.07  0.46]
 [-0.79 -0.24  0.18]
 [-0.09  0.45  0.53]]
A@B= [[ 0.1864  0.4336  1.3423]
 [-0.9825  0.54    1.0097]
 [-0.2682  0.7828  1.0624]]
ik,kj->ij= [[ 0.1864  0.4336  1.3423]
 [-0.9825  0.54    1.0097]
 [-0.2682  0.7828  1.0624]]
A*(B.T)= [[-0.0621  1.1008 -0.7821 -0.0702]
 [ 0.296   0.0301 -0.3216  0.5355]
 [-0.018   0.1288  0.0612  0.8904]]
ij,ji->ij= [[-0.0621  1.1008 -0.7821 -0.0702]
 [ 0.296   0.0301 -0.3216  0.5355]
 [-0.018   0.1288  0.0612  0.8904]]


## Container class

In [9]:
#Local variable holder.
class TLocalVar:
  def __init__(self, l):
    self.__dict__= l

In [13]:
def test_f(a):
  b= 10
  print(locals())
  l= TLocalVar(locals())
  print(l)
  # print(l['a'])
  print(l.a,l.b)
  l.a*= 100
  l.b*= 100
  print(l.a,l.b)
  print(a,b)
  locals()['a']*= 100
  print(a,b)
test_f(100)

{'b': 10, 'a': 100}
100 10
10000 1000
100 10
100 10


In [14]:
#Container class to share variables.
class TContainer(object):
  def __init__(self):
    pass
  def __del__(self):
    pass
  def __str__(self):
    return str(self.__dict__)
  def __repr__(self):
    return str(self.__dict__)
  def __iter__(self):
    return self.__dict__.itervalues()
  def items(self):
    return self.__dict__.items()
  def iteritems(self):
    return self.__dict__.iteritems()
  def keys(self):
    return self.__dict__.keys()
  def values(self):
    return self.__dict__.values()
  def __getitem__(self,key):
    return self.__dict__[key]
  def __setitem__(self,key,value):
    self.__dict__[key]= value
  def __delitem__(self,key):
    del self.__dict__[key]
  def __contains__(self,key):
    return key in self.__dict__
  def Cleanup(self):
    keys= self.__dict__.keys()
    for k in keys:
      self.__dict__[k]= None
      del self.__dict__[k]

In [15]:
l= TContainer()

In [16]:
for l.i in range(3):
  print(l.i)

0
1
2


## Discretization

In [30]:
class TDiscretizer(object):
  def __init__(self, xmin, xmax, n_div):
    self.xmin, self.xmax, self.n_div= xmin, xmax, n_div
    self.dx= (xmax-xmin)/n_div
    self.ptcls_max= torch.tensor(self.n_div-1)
    self.ptcls_min= torch.tensor(0)
  def NumClasses(self):  return self.n_div
  def Encode(self, x):  
    if isinstance(x,torch.Tensor):
      return torch.minimum(self.ptcls_max,torch.maximum(self.ptcls_min,torch.floor((x-self.xmin)/self.dx))).long()
    return np.minimum(self.n_div-1,np.maximum(0,np.floor((x-self.xmin)/self.dx)))
  def Decode(self, c):
    if isinstance(c, torch.Tensor):
      return (self.xmin+0.5*self.dx)+self.dx*torch.minimum(self.ptcls_max,torch.maximum(self.ptcls_min,c))
    return (self.xmin+0.5*self.dx)+self.dx*np.minimum(self.n_div-1,np.maximum(0,c))
disc= TDiscretizer(-2.5, 3.5, 12)
print(f'disc.NumClasses()= {disc.NumClasses()}')
# np.minimum(3,np.array(range(10))), np.minimum(3,0)
# torch.minimum(torch.tensor(3),torch.tensor(range(10))), torch.minimum(3,0)
# torch.tensor(range(10))-4
X= [x for x in np.linspace(-3.,4.,10)]
print(f'X= {X}')
print(f'disc.Encode(x)= {[disc.Encode(x) for x in X]}')
print(f'disc.Encode(np.array(X))= {disc.Encode(np.array(X))}')
print(f'disc.Encode(torch.tensor(X).float())= {disc.Encode(torch.tensor(X).float())}')
C= np.random.randint(-1,15, size=(10))
print(f'C= {C}')
print(f'disc.Decode(c)= {[disc.Decode(c) for c in C]}')
print(f'disc.Decode(np.array(C))= {disc.Decode(np.array(C))}')
print(f'disc.Decode(torch.tensor(C))= {disc.Decode(torch.tensor(C))}')

disc.NumClasses()= 12
X= [-3.0, -2.2222222222222223, -1.4444444444444444, -0.6666666666666665, 0.11111111111111116, 0.8888888888888888, 1.666666666666667, 2.4444444444444446, 3.2222222222222223, 4.0]
disc.Encode(x)= [0.0, 0.0, 2.0, 3.0, 5.0, 6.0, 8.0, 9.0, 11.0, 11.0]
disc.Encode(np.array(X))= [ 0.  0.  2.  3.  5.  6.  8.  9. 11. 11.]
disc.Encode(torch.tensor(X).float())= tensor([ 0,  0,  2,  3,  5,  6,  8,  9, 11, 11])
C= [10  9 -1 11 10  6  4  6  0 -1]
disc.Decode(c)= [2.75, 2.25, -2.25, 3.25, 2.75, 0.75, -0.25, 0.75, -2.25, -2.25]
disc.Decode(np.array(C))= [ 2.75  2.25 -2.25  3.25  2.75  0.75 -0.25  0.75 -2.25 -2.25]
disc.Decode(torch.tensor(C))= tensor([ 2.7500,  2.2500, -2.2500,  3.2500,  2.7500,  0.7500, -0.2500,  0.7500,
        -2.2500, -2.2500])


# Torch Tensor

## shape and view

In [2]:
# n_batch= 1
n_batch= 4

In [3]:
x= torch.tensor(np.zeros((n_batch,3,32,32))).float()

In [4]:
x.shape

torch.Size([4, 3, 32, 32])

In [5]:
x[0].numel()

3072

In [6]:
x.view(x.size(0), -1).shape

torch.Size([4, 3072])

In [7]:
l=torch.nn.Linear(x[0].numel(), 10)
l

Linear(in_features=3072, out_features=10, bias=True)

In [8]:
l(x[0].view(-1))

tensor([ 0.0170, -0.0096, -0.0093, -0.0021,  0.0015,  0.0124,  0.0121,  0.0003,
        -0.0003, -0.0002], grad_fn=<AddBackward0>)

In [9]:
l(x.view(x.size(0), -1))

tensor([[ 0.0170, -0.0096, -0.0093, -0.0021,  0.0015,  0.0124,  0.0121,  0.0003,
         -0.0003, -0.0002],
        [ 0.0170, -0.0096, -0.0093, -0.0021,  0.0015,  0.0124,  0.0121,  0.0003,
         -0.0003, -0.0002],
        [ 0.0170, -0.0096, -0.0093, -0.0021,  0.0015,  0.0124,  0.0121,  0.0003,
         -0.0003, -0.0002],
        [ 0.0170, -0.0096, -0.0093, -0.0021,  0.0015,  0.0124,  0.0121,  0.0003,
         -0.0003, -0.0002]], grad_fn=<AddmmBackward>)

## cat (concatenate) and stack

In [10]:
x1= torch.from_numpy(np.array([2,3,4])).float()
x2= torch.from_numpy(np.array([10,22,12])).float()
print(f'x1={x1}')
print(f'x2={x2}')
print(f'torch.cat={torch.cat((x1,x2),axis=0)}')
print(f'torch.stack={torch.stack((x1,x2),axis=0)}')

x1=tensor([2., 3., 4.])
x2=tensor([10., 22., 12.])
torch.cat=tensor([ 2.,  3.,  4., 10., 22., 12.])
torch.stack=tensor([[ 2.,  3.,  4.],
        [10., 22., 12.]])


## view and flatten

In [113]:
n_batch= 64
x= torch.tensor(np.zeros((n_batch,128,6,6))).float()

In [114]:
x.shape

torch.Size([64, 128, 6, 6])

In [115]:
x.view(x.shape[0], -1).shape

torch.Size([64, 4608])

In [116]:
flatten= torch.nn.Flatten()
flatten(x).shape

torch.Size([64, 4608])

In [117]:
torch.flatten(x,1).shape

torch.Size([64, 4608])

## unflatten

In [122]:
torch.nn.Unflatten(1,(128,6,6))(torch.flatten(x,1)).shape

torch.Size([64, 128, 6, 6])

## Unsqueeze

In [89]:
x= torch.zeros(3,10,10)
x.shape, x.unsqueeze(0).shape

(torch.Size([3, 10, 10]), torch.Size([1, 3, 10, 10]))

# Torch Module

## Sequential

In [10]:
from ay_torch import Noop, TNoop
# print(isinstance(TNoop(),torch.nn.Module))
x= torch.ones(3)
l1= torch.nn.Sequential(torch.nn.Linear(3,3),torch.nn.Linear(3,4))
l2= torch.nn.Sequential(torch.nn.Linear(3,3),None,torch.nn.Linear(3,4))
l2b= torch.nn.Sequential(torch.nn.Linear(3,3),TNoop(),torch.nn.Linear(3,4))
l3= torch.nn.Sequential(*filter(lambda x:x is not None, (torch.nn.Linear(3,3),None,torch.nn.Linear(3,4))))
print(f'l1={l1}')
print(f'l2={l2}')
print(f'l2b={l2b}')
print(f'l3={l3}')
print(f'x={x}')
print(f'l1(x)={l1(x)}')
# print(f'l2(x)={l2(x)}')  #ERROR: TypeError: 'NoneType' object is not callable
print(f'l2b(x)={l2b(x)}')
print(f'l3(x)={l3(x)}')

l1=Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=4, bias=True)
)
l2=Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): None
  (2): Linear(in_features=3, out_features=4, bias=True)
)
l2b=Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): TNoop()
  (2): Linear(in_features=3, out_features=4, bias=True)
)
l3=Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=4, bias=True)
)
x=tensor([1., 1., 1.])
l1(x)=tensor([-0.2396,  0.3478, -0.1649, -0.6443], grad_fn=<AddBackward0>)
l2b(x)=tensor([ 0.1232, -0.1427, -0.7143,  0.4091], grad_fn=<AddBackward0>)
l3(x)=tensor([-0.1548, -0.1635,  0.3904, -0.3709], grad_fn=<AddBackward0>)


In [44]:
# l3.append(torch.nn.Linear(4,3))  #AttributeError: 'Sequential' object has no attribute 'append'
l4= torch.nn.Sequential(l3, torch.nn.Linear(4,3))
print(f'l4={l4}')
print(f'l4(x)={l4(x)}')

l4=Sequential(
  (0): Sequential(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Linear(in_features=3, out_features=4, bias=True)
  )
  (1): Linear(in_features=4, out_features=3, bias=True)
)
l4(x)=tensor([0.4532, 0.0684, 0.5474], grad_fn=<AddBackward0>)


## BatchNormal

In [74]:
x= torch.tensor(range(20))/2.0
x= x[torch.randperm(x.shape[0])].reshape(-1,5)
print(f'x= {x} (shape={x.shape})')
bn= torch.nn.BatchNorm1d(5)
# bn.bias.data.fill_(1e-3)
bn.weight.data.fill_(0.)
# bn.bias.data= torch.Tensor([1.,2.,3.,4.,5.])*0.1
# bn.weight.data= torch.Tensor([5.,4.,3.,2.,1.])*0.1
bn.weight.data.fill_(1.)
print(f'bn(x)= {bn(x)}')

x= tensor([[7.5000, 8.0000, 3.5000, 2.0000, 8.5000],
        [9.0000, 5.0000, 4.0000, 6.5000, 1.0000],
        [9.5000, 5.5000, 3.0000, 1.5000, 0.5000],
        [7.0000, 0.0000, 6.0000, 4.5000, 2.5000]]) (shape=torch.Size([4, 5]))
bn(x)= tensor([[-0.7276,  1.1630, -0.5488, -0.8078,  1.6853],
        [ 0.7276,  0.1292, -0.1098,  1.4291, -0.6663],
        [ 1.2127,  0.3015, -0.9879, -1.0563, -0.8231],
        [-1.2127, -1.5937,  1.6465,  0.4350, -0.1960]],
       grad_fn=<NativeBatchNormBackward>)


In [75]:
bn.weight.data, bn.bias.data

(tensor([1., 1., 1., 1., 1.]), tensor([0., 0., 0., 0., 0.]))

In [77]:
torch.mean(x,axis=0), torch.var(x,axis=0)
(x-torch.mean(x,axis=0))/torch.sqrt(torch.var(x,axis=0)) * bn.weight + bn.bias

tensor([[-0.6301,  1.0072, -0.4753, -0.6996,  1.4595],
        [ 0.6301,  0.1119, -0.0951,  1.2377, -0.5770],
        [ 1.0502,  0.2611, -0.8555, -0.9148, -0.7128],
        [-1.0502, -1.3802,  1.4259,  0.3767, -0.1697]], grad_fn=<AddBackward0>)

In [82]:
inn= torch.nn.InstanceNorm1d(5, affine=True)
# inn.bias.data.fill_(1e-3)
# inn.weight.data.fill_(0.)
# inn.bias.data= torch.Tensor([1.,2.,3.,4.,5.])*0.1
# inn.weight.data= torch.Tensor([5.,4.,3.,2.,1.])*0.1
# inn.weight.data.fill_(1.)
print(f'inn(x)= {inn(x)}')

ValueError: InstanceNorm1d returns 0-filled tensor to 2D tensor.This is because InstanceNorm1d reshapes inputs to(1, N * C, ...) from (N, C,...) and this makesvariances 0.

## Max module

In [91]:
x= torch.tensor(range(150))/2.0
x= x[torch.randperm(x.shape[0])].reshape(-1,3,5,5)
x

tensor([[[[59.0000, 17.0000, 55.5000, 56.5000, 58.5000],
          [24.0000, 39.5000, 50.5000, 62.0000, 72.5000],
          [28.0000, 42.5000, 41.0000, 51.0000, 36.5000],
          [54.0000, 70.0000, 35.5000, 20.0000, 28.5000],
          [26.0000, 16.0000,  6.0000, 70.5000, 49.0000]],

         [[19.0000,  0.0000, 23.0000, 48.5000, 14.0000],
          [65.5000, 36.0000,  4.0000, 64.0000, 12.0000],
          [25.0000, 34.0000, 35.0000,  2.5000, 30.5000],
          [61.0000, 54.5000, 25.5000, 60.0000, 69.0000],
          [65.0000,  1.5000, 68.0000, 45.0000, 32.0000]],

         [[19.5000, 31.0000, 57.5000, 13.0000, 46.0000],
          [55.0000, 14.5000, 53.5000,  2.0000, 43.5000],
          [49.5000, 67.5000, 46.5000, 15.5000, 61.5000],
          [34.5000,  3.0000, 10.5000, 44.0000,  1.0000],
          [ 9.0000, 38.5000, 60.5000, 33.5000, 72.0000]]],


        [[[33.0000, 73.5000, 41.5000,  4.5000, 18.5000],
          [31.5000,  3.5000,  5.0000, 63.0000, 62.5000],
          [69.5000, 23.

In [99]:
torch.max(x, axis=1)[0].unsqueeze(1).shape

torch.Size([2, 1, 5, 5])

In [103]:
class TMax(torch.nn.Module):
  def forward(self, x):
    return torch.max(x, axis=1)[0].unsqueeze(1)

In [104]:
m= TMax()
m(x)

tensor([[[[59.0000, 31.0000, 57.5000, 56.5000, 58.5000],
          [65.5000, 39.5000, 53.5000, 64.0000, 72.5000],
          [49.5000, 67.5000, 46.5000, 51.0000, 61.5000],
          [61.0000, 70.0000, 35.5000, 60.0000, 69.0000],
          [65.0000, 38.5000, 68.0000, 70.5000, 72.0000]]],


        [[[68.5000, 73.5000, 67.0000, 26.5000, 66.0000],
          [31.5000, 51.5000, 57.0000, 66.5000, 62.5000],
          [69.5000, 58.0000, 71.0000, 71.5000, 24.5000],
          [16.5000, 64.5000, 56.0000, 48.0000, 47.5000],
          [40.0000, 74.0000, 74.5000, 53.0000, 52.5000]]]])

## AvgPool2d and Upsample

In [124]:
img= torch.from_numpy(np.random.uniform(0,1,size=(1,1,8,8))).float()
print(img.shape)
img

torch.Size([1, 1, 8, 8])


tensor([[[[0.2388, 0.1915, 0.6603, 0.9222, 0.2945, 0.0357, 0.7832, 0.1920],
          [0.4177, 0.8654, 0.8985, 0.7739, 0.7018, 0.4917, 0.0838, 0.7546],
          [0.2234, 0.6977, 0.2054, 0.9994, 0.8951, 0.7883, 0.3776, 0.6775],
          [0.4321, 0.6387, 0.0568, 0.0692, 0.7113, 0.3858, 0.5290, 0.1512],
          [0.7873, 0.7903, 0.5976, 0.1046, 0.5114, 0.9380, 0.3291, 0.2403],
          [0.2715, 0.7936, 0.8609, 0.6254, 0.4417, 0.2772, 0.4428, 0.8376],
          [0.5523, 0.5319, 0.9425, 0.3161, 0.6561, 0.8714, 0.4156, 0.9550],
          [0.4729, 0.7059, 0.4009, 0.0883, 0.2010, 0.8251, 0.3593, 0.3616]]]])

In [125]:
img2= torch.nn.AvgPool2d(kernel_size=2, stride=None, padding=0, ceil_mode=True)(img)
print(img2.shape)
img2

torch.Size([1, 1, 4, 4])


tensor([[[[0.4283, 0.8137, 0.3809, 0.4534],
          [0.4980, 0.3327, 0.6951, 0.4338],
          [0.6607, 0.5471, 0.5421, 0.4624],
          [0.5658, 0.4369, 0.6384, 0.5228]]]])

In [126]:
img3= torch.nn.Upsample(scale_factor=2, mode='nearest', align_corners=None)(img2)
print(img3.shape)
img3

torch.Size([1, 1, 8, 8])


tensor([[[[0.4283, 0.4283, 0.8137, 0.8137, 0.3809, 0.3809, 0.4534, 0.4534],
          [0.4283, 0.4283, 0.8137, 0.8137, 0.3809, 0.3809, 0.4534, 0.4534],
          [0.4980, 0.4980, 0.3327, 0.3327, 0.6951, 0.6951, 0.4338, 0.4338],
          [0.4980, 0.4980, 0.3327, 0.3327, 0.6951, 0.6951, 0.4338, 0.4338],
          [0.6607, 0.6607, 0.5471, 0.5471, 0.5421, 0.5421, 0.4624, 0.4624],
          [0.6607, 0.6607, 0.5471, 0.5471, 0.5421, 0.5421, 0.4624, 0.4624],
          [0.5658, 0.5658, 0.4369, 0.4369, 0.6384, 0.6384, 0.5228, 0.5228],
          [0.5658, 0.5658, 0.4369, 0.4369, 0.6384, 0.6384, 0.5228, 0.5228]]]])

In [131]:
img4= torch.nn.Upsample(size=(10,10), mode='nearest', align_corners=None)(img2)
print(img4.shape)
img4

torch.Size([1, 1, 10, 10])


tensor([[[[0.4283, 0.4283, 0.4283, 0.8137, 0.8137, 0.3809, 0.3809, 0.3809,
           0.4534, 0.4534],
          [0.4283, 0.4283, 0.4283, 0.8137, 0.8137, 0.3809, 0.3809, 0.3809,
           0.4534, 0.4534],
          [0.4283, 0.4283, 0.4283, 0.8137, 0.8137, 0.3809, 0.3809, 0.3809,
           0.4534, 0.4534],
          [0.4980, 0.4980, 0.4980, 0.3327, 0.3327, 0.6951, 0.6951, 0.6951,
           0.4338, 0.4338],
          [0.4980, 0.4980, 0.4980, 0.3327, 0.3327, 0.6951, 0.6951, 0.6951,
           0.4338, 0.4338],
          [0.6607, 0.6607, 0.6607, 0.5471, 0.5471, 0.5421, 0.5421, 0.5421,
           0.4624, 0.4624],
          [0.6607, 0.6607, 0.6607, 0.5471, 0.5471, 0.5421, 0.5421, 0.5421,
           0.4624, 0.4624],
          [0.6607, 0.6607, 0.6607, 0.5471, 0.5471, 0.5421, 0.5421, 0.5421,
           0.4624, 0.4624],
          [0.5658, 0.5658, 0.5658, 0.4369, 0.4369, 0.6384, 0.6384, 0.6384,
           0.5228, 0.5228],
          [0.5658, 0.5658, 0.5658, 0.4369, 0.4369, 0.6384, 0.6384, 0.6384

## Unfold+bmm and Conv2d

In [16]:
# img= torch.from_numpy(np.random.uniform(0,1,size=(1,1,4,4))).float()
img= torch.tensor(range(16)).float().reshape(1,1,4,4)
print(img.shape)
img

torch.Size([1, 1, 4, 4])


tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [21]:
unfold= torch.nn.Unfold(kernel_size=(2,2))
print(f'parameters: {[p for p in unfold.parameters()]}')
img_u= unfold(img)
print(img_u.shape)
img_u

parameters: []
torch.Size([1, 4, 9])


tensor([[[ 0.,  1.,  2.,  4.,  5.,  6.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  5.,  6.,  7.,  9., 10., 11.],
         [ 4.,  5.,  6.,  8.,  9., 10., 12., 13., 14.],
         [ 5.,  6.,  7.,  9., 10., 11., 13., 14., 15.]]])

In [51]:
conv= torch.nn.Conv2d(in_channels=1,out_channels=1,kernel_size=(2,2),bias=False)
print(f'weight: {conv.weight.data}')
print(f'unfold(weight): {unfold(conv.weight.data)}, {unfold(conv.weight.data).shape}')

weight: tensor([[[[-0.4410, -0.1046],
          [ 0.4316,  0.4210]]]])
unfold(weight): tensor([[[-0.4410],
         [-0.1046],
         [ 0.4316],
         [ 0.4210]]]), torch.Size([1, 4, 1])


In [59]:
print(f'conv(img): {conv(img)}')
torch.bmm(img_u.transpose(2,1), unfold(conv.weight.data)).view(-1,1,3,3)

conv(img): tensor([[[[3.7269, 4.0339, 4.3409],
          [4.9549, 5.2619, 5.5690],
          [6.1830, 6.4900, 6.7970]]]], grad_fn=<ThnnConv2DBackward>)


tensor([[[[3.7269, 4.0339, 4.3409],
          [4.9549, 5.2619, 5.5690],
          [6.1830, 6.4900, 6.7970]]]])

## Convolution

In [112]:
from ay_torch import ConvLayer

In [32]:
img= torch.from_numpy(np.random.uniform(0,1,size=(1,1,8,8))).float()
img

tensor([[[[0.2839, 0.8808, 0.0139, 0.8287, 0.5301, 0.6634, 0.6912, 0.9814],
          [0.1733, 0.3598, 0.4103, 0.4994, 0.0770, 0.8473, 0.9285, 0.0275],
          [0.3501, 0.0781, 0.8500, 0.1458, 0.3770, 0.5725, 0.0959, 0.7596],
          [0.3627, 0.7821, 0.7763, 0.7251, 0.4945, 0.2048, 0.5201, 0.4572],
          [0.2111, 0.1763, 0.3066, 0.7494, 0.9515, 0.7900, 0.2000, 0.5780],
          [0.3230, 0.6924, 0.6222, 0.3055, 0.3279, 0.3511, 0.2773, 0.9002],
          [0.1326, 0.8908, 0.0514, 0.3623, 0.6731, 0.9318, 0.0854, 0.5532],
          [0.4673, 0.3573, 0.9547, 0.6804, 0.6719, 0.8438, 0.7647, 0.1715]]]])

In [33]:
# ConvLayer(1,3,3)(img)
# ConvLayer(1,1,3,transpose=True)(img)
print(ConvLayer(3,1,3,transpose=True)(ConvLayer(1,3,3)(img)))
print(img.shape, ConvLayer(1,3,3)(img).shape, ConvLayer(3,1,3,transpose=True)(ConvLayer(1,3,3)(img)).shape)

tensor([[[[1.0390, 0.8798, 0.0000, 0.1952, 1.0140, 0.0000, 0.0000, 1.3001],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.1778, 1.4182],
          [0.4135, 0.0000, 0.0000, 0.1114, 0.0000, 0.0000, 1.1794, 0.3791],
          [0.0000, 0.5827, 1.8779, 0.4145, 0.0000, 0.0203, 0.0000, 1.8402],
          [0.0000, 0.0000, 0.0000, 0.0000, 1.6081, 1.3924, 0.0000, 0.5100],
          [0.0000, 0.0000, 0.7051, 0.4953, 0.0000, 0.1407, 0.0000, 1.0345],
          [0.0000, 0.0000, 0.0998, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.3873, 1.3679, 0.8526, 0.6056, 0.1805, 1.2865, 1.7175, 0.3159]]]],
       grad_fn=<ReluBackward1>)
torch.Size([1, 1, 8, 8]) torch.Size([1, 3, 8, 8]) torch.Size([1, 1, 8, 8])


In [34]:
print(ConvLayer(1,3,3,stride=2)(img))
print(ConvLayer(3,1,3,stride=2,transpose=True)(ConvLayer(1,3,3,stride=2)(img)))
print(img.shape, ConvLayer(1,3,3,stride=2)(img).shape, ConvLayer(3,1,3,stride=2,transpose=True)(ConvLayer(1,3,3,stride=2)(img)).shape)

tensor([[[[1.2139, 0.0000, 0.1058, 0.0000],
          [0.3911, 0.0000, 1.5457, 0.0000],
          [0.8706, 0.1721, 0.0000, 0.0000],
          [1.2724, 0.0000, 0.0813, 0.0000]],

         [[0.9741, 0.0000, 1.2964, 0.0000],
          [0.6860, 0.2006, 0.0000, 0.0000],
          [0.0000, 0.0000, 1.2277, 0.2832],
          [0.0000, 0.0000, 1.4465, 0.0000]],

         [[0.0000, 0.9920, 0.0000, 1.9861],
          [0.0000, 0.0000, 0.7416, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.9116, 0.0000, 2.2223]]]], grad_fn=<ReluBackward1>)
tensor([[[[0.0000, 0.0000, 0.0000, 0.4904, 0.0000, 0.0000, 0.0000, 2.1680],
          [0.2877, 0.6108, 0.1776, 0.6291, 0.0000, 4.0315, 0.9366, 3.0488],
          [0.2264, 1.2161, 0.3334, 0.0000, 0.0000, 0.0000, 0.0000, 0.0207],
          [0.0000, 1.0006, 0.0000, 0.6195, 0.0000, 0.5516, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5167, 0.0000, 0.0000],
          [0.0000, 0.3972, 0.0000, 0.0111, 0.0000, 0.0000, 0

## ResBlock

In [97]:
from ay_torch import TResBlock

In [98]:
print(img.shape)
torchinfo.summary(TResBlock(1,1,3),img.shape)
# TResBlock(1,1,3)(img)

torch.Size([1, 1, 8, 8])


Layer (type:depth-idx)                   Output Shape              Param #
TResBlock                                --                        --
├─Sequential: 1-1                        [1, 3, 8, 8]              --
│    └─Sequential: 2-1                   [1, 3, 8, 8]              --
│    │    └─Conv2d: 3-1                  [1, 3, 8, 8]              27
│    │    └─BatchNorm2d: 3-2             [1, 3, 8, 8]              6
│    │    └─ReLU: 3-3                    [1, 3, 8, 8]              --
│    └─Sequential: 2-2                   [1, 3, 8, 8]              --
│    │    └─Conv2d: 3-4                  [1, 3, 8, 8]              81
│    │    └─BatchNorm2d: 3-5             [1, 3, 8, 8]              6
├─Sequential: 1-2                        [1, 3, 8, 8]              --
│    └─Sequential: 2-3                   [1, 3, 8, 8]              --
│    │    └─Conv2d: 3-6                  [1, 3, 8, 8]              3
│    │    └─BatchNorm2d: 3-7             [1, 3, 8, 8]              6
├─ReLU: 1-3        

In [99]:
img2= TResBlock(1,1,3)(img)
print(img2.shape)
torchinfo.summary(TResBlock(1,3,1,transpose=True),img2.shape)
# TResBlock(1,3,1)(img2)

torch.Size([1, 3, 8, 8])


Layer (type:depth-idx)                   Output Shape              Param #
TResBlock                                --                        --
├─Sequential: 1-1                        [1, 1, 8, 8]              --
│    └─Sequential: 2-1                   [1, 1, 8, 8]              --
│    │    └─ConvTranspose2d: 3-1         [1, 1, 8, 8]              27
│    │    └─BatchNorm2d: 3-2             [1, 1, 8, 8]              2
│    │    └─ReLU: 3-3                    [1, 1, 8, 8]              --
│    └─Sequential: 2-2                   [1, 1, 8, 8]              --
│    │    └─ConvTranspose2d: 3-4         [1, 1, 8, 8]              9
│    │    └─BatchNorm2d: 3-5             [1, 1, 8, 8]              2
├─Sequential: 1-2                        [1, 1, 8, 8]              --
│    └─Sequential: 2-3                   [1, 1, 8, 8]              --
│    │    └─ConvTranspose2d: 3-6         [1, 1, 8, 8]              3
│    │    └─BatchNorm2d: 3-7             [1, 1, 8, 8]              2
├─ReLU: 1-3         

In [102]:
print(img.shape)
torchinfo.summary(TResBlock(1,1,3,stride=2),img.shape)
# TResBlock(1,1,3,stride=2)(img)
# rb= TResBlock(1,1,3,stride=2)
# rb.convpath(img).shape
# rb.idpath(img).shape
# rb

torch.Size([1, 1, 8, 8])


Layer (type:depth-idx)                   Output Shape              Param #
TResBlock                                --                        --
├─Sequential: 1-1                        [1, 3, 4, 4]              --
│    └─Sequential: 2-1                   [1, 3, 4, 4]              --
│    │    └─Conv2d: 3-1                  [1, 3, 4, 4]              27
│    │    └─BatchNorm2d: 3-2             [1, 3, 4, 4]              6
│    │    └─ReLU: 3-3                    [1, 3, 4, 4]              --
│    └─Sequential: 2-2                   [1, 3, 4, 4]              --
│    │    └─Conv2d: 3-4                  [1, 3, 4, 4]              81
│    │    └─BatchNorm2d: 3-5             [1, 3, 4, 4]              6
├─Sequential: 1-2                        [1, 3, 4, 4]              --
│    └─AvgPool2d: 2-3                    [1, 1, 4, 4]              --
│    └─Sequential: 2-4                   [1, 3, 4, 4]              --
│    │    └─Conv2d: 3-6                  [1, 3, 4, 4]              3
│    │    └─BatchN

In [111]:
img2= TResBlock(1,1,3,stride=2)(img)
print(img2.shape)
torchinfo.summary(TResBlock(1,3,1,stride=2,transpose=True),img2.shape)
# TResBlock(1,3,1,stride=2,transpose=True)(img2)
# rb= TResBlock(1,3,1,stride=2,transpose=True,upsample_first=True)
# print(rb.convpath(img2).shape)
# print(rb.idpath(img2).shape)
# rb

torch.Size([1, 3, 4, 4])


Layer (type:depth-idx)                   Output Shape              Param #
TResBlock                                --                        --
├─Sequential: 1-1                        [1, 1, 8, 8]              --
│    └─Sequential: 2-1                   [1, 1, 8, 8]              --
│    │    └─ConvTranspose2d: 3-1         [1, 1, 8, 8]              27
│    │    └─BatchNorm2d: 3-2             [1, 1, 8, 8]              2
│    │    └─ReLU: 3-3                    [1, 1, 8, 8]              --
│    └─Sequential: 2-2                   [1, 1, 8, 8]              --
│    │    └─ConvTranspose2d: 3-4         [1, 1, 8, 8]              9
│    │    └─BatchNorm2d: 3-5             [1, 1, 8, 8]              2
├─Sequential: 1-2                        [1, 1, 8, 8]              --
│    └─Sequential: 2-3                   [1, 1, 4, 4]              --
│    │    └─ConvTranspose2d: 3-6         [1, 1, 4, 4]              3
│    │    └─BatchNorm2d: 3-7             [1, 1, 4, 4]              2
│    └─Upsample: 2-4

## ResNet without pooling

In [19]:
from ay_torch import TResBlock, TResNet, TNoop

In [35]:
img= torch.from_numpy(np.random.uniform(0,1,size=(2,1,8,8))).float()
img

tensor([[[[0.6807, 0.6319, 0.1488, 0.2314, 0.1645, 0.2275, 0.8301, 0.4215],
          [0.8867, 0.2966, 0.9344, 0.6837, 0.9192, 0.1543, 0.9079, 0.7589],
          [0.8372, 0.8294, 0.2528, 0.7335, 0.8887, 0.3479, 0.5266, 0.9375],
          [0.7423, 0.2302, 0.8697, 0.0619, 0.1730, 0.6311, 0.1207, 0.5635],
          [0.4931, 0.7887, 0.2703, 0.6939, 0.4062, 0.9014, 0.7710, 0.3900],
          [0.5141, 0.9686, 0.1900, 0.2002, 0.1720, 0.5338, 0.1929, 0.7724],
          [0.9152, 0.2015, 0.0836, 0.3036, 0.2042, 0.3879, 0.0426, 0.1872],
          [0.9524, 0.5482, 0.6289, 0.8618, 0.2832, 0.5301, 0.9718, 0.6986]]],


        [[[0.4640, 0.2365, 0.9946, 0.7539, 0.0234, 0.3142, 0.6843, 0.0659],
          [0.1769, 0.6768, 0.4790, 0.5934, 0.4234, 0.1729, 0.3388, 0.0212],
          [0.4978, 0.1483, 0.8279, 0.4131, 0.3294, 0.4945, 0.3556, 0.1566],
          [0.6589, 0.4510, 0.2039, 0.9783, 0.6589, 0.1906, 0.8111, 0.5160],
          [0.6891, 0.9937, 0.1032, 0.4532, 0.0265, 0.9145, 0.3716, 0.3260],
        

In [42]:
print(img.shape)
# TResNet(TResBlock,1,[2,2,2,2],in_channels=1,out_channels=1)(img)
print(torchinfo.summary(TResNet(TResBlock,1,[2,2,2,2],in_channels=1,out_channels=1,rnpool=TNoop),img.shape))
# print(torchinfo.summary(TResBlock(1,1,3,stride=2,pool=TNoop),img.shape))
# TResBlock(1,1,3)(img)

torch.Size([2, 1, 8, 8])
Layer (type:depth-idx)                        Output Shape              Param #
TResNet                                       --                        --
├─Sequential: 1-1                             [2, 32, 8, 8]             --
│    └─Conv2d: 2-1                            [2, 32, 8, 8]             288
│    └─BatchNorm2d: 2-2                       [2, 32, 8, 8]             64
│    └─ReLU: 2-3                              [2, 32, 8, 8]             --
├─Sequential: 1-2                             [2, 32, 4, 4]             --
│    └─Conv2d: 2-4                            [2, 32, 4, 4]             9,216
│    └─BatchNorm2d: 2-5                       [2, 32, 4, 4]             64
│    └─ReLU: 2-6                              [2, 32, 4, 4]             --
├─Sequential: 1-3                             [2, 64, 2, 2]             --
│    └─Conv2d: 2-7                            [2, 64, 2, 2]             18,432
│    └─BatchNorm2d: 2-8                       [2, 64, 2, 2]   

# Torch functions

## Softmax and clamp

In [143]:
img= torch.from_numpy(np.random.uniform(-1,1,size=(1,1,5,5)))
img

tensor([[[[ 0.1590, -0.4883,  0.0481, -0.2388, -0.4310],
          [-0.2900,  0.2253, -0.2798,  0.2368,  0.6311],
          [-0.4764,  0.6701,  0.8507,  0.3041,  0.8848],
          [ 0.0155, -0.5271, -0.7959,  0.2696,  0.9397],
          [ 0.2211,  0.3824, -0.3784,  0.1784,  0.5068]]]],
       dtype=torch.float64)

In [144]:
torch.sigmoid(img)

tensor([[[[0.5397, 0.3803, 0.5120, 0.4406, 0.3939],
          [0.4280, 0.5561, 0.4305, 0.5589, 0.6527],
          [0.3831, 0.6615, 0.7007, 0.5754, 0.7078],
          [0.5039, 0.3712, 0.3109, 0.5670, 0.7190],
          [0.5551, 0.5945, 0.4065, 0.5445, 0.6240]]]], dtype=torch.float64)

In [145]:
torch.clamp(img,0,1)

tensor([[[[0.1590, 0.0000, 0.0481, 0.0000, 0.0000],
          [0.0000, 0.2253, 0.0000, 0.2368, 0.6311],
          [0.0000, 0.6701, 0.8507, 0.3041, 0.8848],
          [0.0155, 0.0000, 0.0000, 0.2696, 0.9397],
          [0.2211, 0.3824, 0.0000, 0.1784, 0.5068]]]], dtype=torch.float64)

## Loss and reduction

In [32]:
y_pred= torch.randn((5,1))
y_trg= torch.randn((5,1))
# f_loss= torch.nn.functional.l1_loss
f_loss= torch.nn.functional.mse_loss
print(f'y_pred= {y_pred.T}')
print(f'y_trg= {y_trg.T}')
print(f'loss(mean)= {f_loss(y_pred,y_trg,reduction="mean")}')
print(f'loss(sum)= {f_loss(y_pred,y_trg,reduction="sum")}')
print(f'loss(none)= {f_loss(y_pred,y_trg,reduction="none").T}')

y_pred= tensor([[ 0.0474, -0.8917,  0.4548,  0.7686,  0.3054]])
y_trg= tensor([[-1.1532,  0.4937,  1.0670,  0.5567, -0.9121]])
loss(mean)= 1.0526280403137207
loss(sum)= 5.2631402015686035
loss(none)= tensor([[1.4415, 1.9195, 0.3748, 0.0449, 1.4824]])


### Weighted average loss

In [33]:
def weighted_average_loss(pred, trg, w):
  return torch.sum(w*f_loss(pred,trg,reduction='none'))/torch.sum(w)
weight= torch.ones((5,1))
print(f'weight= {weight.T}')
print(f'weighted_average_loss= {weighted_average_loss(y_pred,y_trg,weight)}')
weight= torch.from_numpy(np.random.uniform(0,1,size=(5,1))).float()
print(f'weight= {weight.T}')
print(f'weighted_average_loss= {weighted_average_loss(y_pred,y_trg,weight)}')

weight= tensor([[1., 1., 1., 1., 1.]])
weighted_average_loss= 1.0526280403137207
weight= tensor([[0.8862, 0.8221, 0.7881, 0.0985, 0.5323]])
weighted_average_loss= 1.2612899541854858


## torch.heaviside

In [37]:
x= torch.tensor([0.1,0.1,1.0,1.0,0.1])
print(f'x= {x}')
torch.heaviside(x-0.5,torch.tensor([0.5]))

x= tensor([0.1000, 0.1000, 1.0000, 1.0000, 0.1000])


tensor([0., 0., 1., 1., 0.])

## torch.nn.functional.threshold

In [39]:
x= torch.tensor([0.1,0.1,1.0,1.0,0.1])
print(f'x= {x}')
torch.nn.functional.threshold(x,0.5,0,inplace=True)

x= tensor([0.1000, 0.1000, 1.0000, 1.0000, 0.1000])


tensor([0., 0., 1., 1., 0.])

# Torch test

## Range Loss

In [42]:
y1,y2,y_trg= (torch.round(torch.randn((5,1))*100.) for _ in range(3))
print(f'y1= {y1.T}')
print(f'y2= {y2.T}')
print(f'y_trg= {y_trg.T}')

y1= tensor([[ 90., -67.,  79.,  32.,  -1.]])
y2= tensor([[ -69.,  -32.,  -50., -224., -183.]])
y_trg= tensor([[ 82.,   2.,  71., 158., 138.]])


In [53]:
berr1= torch.logical_and(y1<y_trg, y_trg<y2)
berr2= torch.logical_and(y2<y_trg, y_trg<y1)
berr= torch.logical_or(berr1, berr2)
print(f'berr1= {berr1.T}')
print(f'berr2= {berr2.T}')
print(f'berr= {berr.T}')

berr1= tensor([[False, False, False, False, False]])
berr2= tensor([[ True, False,  True, False, False]])
berr= tensor([[ True, False,  True, False, False]])


In [55]:
err1= torch.min(torch.abs(y_trg-y1), torch.abs(y_trg-y2))[torch.logical_and(y1<y_trg, y_trg<y2)]
err2= torch.min(torch.abs(y_trg-y1), torch.abs(y_trg-y2))[torch.logical_and(y2<y_trg, y_trg<y1)]
print(f'err1= {err1.T}')
print(f'err2= {err2.T}')

err1= tensor([])
err2= tensor([8., 8.])


In [60]:
err1,err2= y_trg-y1, y_trg-y2
berr= err1*err2>0
err= torch.min(torch.abs(err1[berr]), torch.abs(err2[berr]))
print(f'berr= {berr.T}')
print(f'err= {err.T}')
torch.sum(err)/len(berr)

berr= tensor([[False,  True, False,  True,  True]])
err= tensor([ 34., 126., 139.])


tensor(59.8000)

In [62]:
ymin,ymax= torch.min(y1,y2),torch.max(y1,y2)
err= torch.nn.functional.threshold(ymin-y_trg,0.0,0,inplace=True)+torch.nn.functional.threshold(y_trg-ymax,0.0,0,inplace=True)
print(f'ymin= {ymin.T}')
print(f'ymax= {ymax.T}')
print(f'err= {err.T}')
torch.mean(err)

ymin= tensor([[ -69.,  -67.,  -50., -224., -183.]])
ymax= tensor([[ 90., -32.,  79.,  32.,  -1.]])
err= tensor([[  0.,  34.,   0., 126., 139.]])


tensor(59.8000)

In [66]:
ymin,ymax= torch.min(y1,y2),torch.max(y1,y2)
yout_err= torch.nn.functional.threshold(ymin-y_trg,0.0,0,inplace=True)+torch.nn.functional.threshold(y_trg-ymax,0.0,0,inplace=True)
y_err= torch.abs(y_trg-ymin)+torch.abs(y_trg-ymax)
print(f'yout_err= {yout_err.T}')
print(f'y_err= {y_err.T}')
print(f'torch.mean(yout_err**2)= {torch.mean(yout_err**2)}')
print(f'torch.mean(yout_err**2+y_err**2)= {torch.mean(yout_err**2+y_err**2)}')
print(f'torch.mean(yout_err**2+0.1*y_err**2)= {torch.mean(yout_err**2+0.1*y_err**2)}')
print(f'torch.mean(yout_err)= {torch.mean(yout_err)}')
print(f'torch.mean(yout_err+y_err)= {torch.mean(yout_err+y_err)}')
print(f'torch.mean(yout_err+0.1*y_err)= {torch.mean(yout_err+0.1*y_err)}')

yout_err= tensor([[  0.,  34.,   0., 126., 139.]])
y_err= tensor([[159., 103., 129., 508., 460.]])
torch.mean(yout_err**2)= 7270.60009765625
torch.mean(yout_err**2+y_err**2)= 111709.6015625
torch.mean(yout_err**2+0.1*y_err**2)= 17714.5
torch.mean(yout_err)= 59.79999923706055
torch.mean(yout_err+y_err)= 331.6000061035156
torch.mean(yout_err+0.1*y_err)= 86.9800033569336
